# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-03 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='S3store',
        ),
        migrations.DeleteModel(
            name='Translatioin',
        ),
    ]
